// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: moonloop/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the moonloop module's genesis state.
type GenesisState struct {
	CollectionList      []Collection      `protobuf:"bytes,1,rep,name=collectionList,proto3" json:"collectionList"`
	ClassList           []Class           `protobuf:"bytes,2,rep,name=classList,proto3" json:"classList"`
	MintStrategyList    []MintStrategy    `protobuf:"bytes,3,rep,name=mintStrategyList,proto3" json:"mintStrategyList"`
	ContributionList    []Contribution    `protobuf:"bytes,4,rep,name=contributionList,proto3" json:"contributionList"`
	PowerupTemplateList []PowerupTemplate `protobuf:"bytes,5,rep,name=powerupTemplateList,proto3" json:"powerupTemplateList"`
	PowerupList         []Powerup         `protobuf:"bytes,6,rep,name=powerupList,proto3" json:"powerupList"`
	ClassTemplateList   []ClassTemplate   `protobuf:"bytes,7,rep,name=classTemplateList,proto3" json:"classTemplateList"`
	CollectionOwnerList []CollectionOwner `protobuf:"bytes,8,rep,name=collectionOwnerList,proto3" json:"collectionOwnerList"`
	InstanceOwnerList   []InstanceOwner   `protobuf:"bytes,9,rep,name=instanceOwnerList,proto3" json:"instanceOwnerList"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2c2893216e0ba1c, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetCollectionList() []Collection {
	if m != nil {
		return m.CollectionList
	}
	return nil
}

func (m *GenesisState) GetClassList() []Class {
	if m != nil {
		return m.ClassList
	}
	return nil
}

func (m *GenesisState) GetMintStrategyList() []MintStrategy {
	if m != nil {
		return m.MintStrategyList
	}
	return nil
}

func (m *GenesisState) GetContributionList() []Contribution {
	if m != nil {
		return m.ContributionList
	}
	return nil
}

func (m *GenesisState) GetPowerupTemplateList() []PowerupTemplate {
	if m != nil {
		return m.PowerupTemplateList
	}
	return nil
}

func (m *GenesisState) GetPowerupList() []Powerup {
	if m != nil {
		return m.PowerupList
	}
	return nil
}

func (m *GenesisState) GetClassTemplateList() []ClassTemplate {
	if m != nil {
		return m.ClassTemplateList
	}
	return nil
}

func (m *GenesisState) GetCollectionOwnerList() []CollectionOwner {
	if m != nil {
		return m.CollectionOwnerList
	}
	return nil
}

func (m *GenesisState) GetInstanceOwnerList() []InstanceOwner {
	if m != nil {
		return m.InstanceOwnerList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "str11ngfello.moonloop.moonloop.GenesisState")
}

func init() { proto.RegisterFile("moonloop/genesis.proto", fileDescriptor_d2c2893216e0ba1c) }

var fileDescriptor_d2c2893216e0ba1c = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x86, 0x93, 0xdb, 0xde, 0xde, 0xdb, 0xa9, 0x88, 0xc6, 0x52, 0xb4, 0x6a, 0x2a, 0x82, 0x28,
	0xa2, 0x09, 0xd5, 0x37, 0x68, 0x17, 0x52, 0x54, 0x2a, 0xd6, 0x85, 0xb8, 0xb0, 0xa4, 0x61, 0x8c,
	0x81, 0x64, 0x26, 0x64, 0xa6, 0xd4, 0xbe, 0x85, 0x8f, 0xd5, 0x65, 0x97, 0x2e, 0x44, 0xa4, 0x7d,
	0x11, 0xc9, 0x74, 0x92, 0x4c, 0x92, 0x62, 0xb3, 0x3b, 0x9c, 0x33, 0xff, 0xf7, 0xcf, 0x39, 0x67,
	0x06, 0xd4, 0x5c, 0x8c, 0x91, 0x83, 0xb1, 0xa7, 0x5b, 0x10, 0x41, 0x62, 0x13, 0xcd, 0xf3, 0x31,
	0xc5, 0x8a, 0x4a, 0xa8, 0xdf, 0x6c, 0x22, 0xeb, 0x05, 0x3a, 0x0e, 0xd6, 0xc2, 0x43, 0x51, 0x50,
	0xdf, 0x89, 0x74, 0x26, 0x76, 0x1c, 0x68, 0x52, 0x1b, 0xa3, 0x85, 0xb4, 0x5e, 0x8d, 0x4b, 0x8e,
	0x41, 0x38, 0xb0, 0xbe, 0x17, 0x65, 0x5d, 0x1b, 0xd1, 0x3e, 0xa1, 0xbe, 0x41, 0xa1, 0x35, 0xe6,
	0xd5, 0x5d, 0x01, 0x87, 0xa8, 0x6f, 0x0f, 0x86, 0x02, 0xb0, 0x11, 0x15, 0x3d, 0x3c, 0x82, 0xfe,
	0xd0, 0xeb, 0x53, 0xe8, 0x7a, 0x8e, 0x41, 0x21, 0x3f, 0x50, 0x4b, 0x1f, 0xe0, 0xf9, 0xfd, 0xe4,
	0x4d, 0xd2, 0xb2, 0xc6, 0x92, 0x1e, 0xfa, 0x78, 0x84, 0xa0, 0x9f, 0xd1, 0xdb, 0x88, 0x50, 0x03,
	0x99, 0x30, 0x51, 0xae, 0x5a, 0xd8, 0xc2, 0x2c, 0xd4, 0x83, 0x68, 0x91, 0x3d, 0xfc, 0x2c, 0x81,
	0xb5, 0xab, 0xc5, 0x2c, 0x7b, 0xd4, 0xa0, 0x50, 0x79, 0x04, 0xeb, 0x31, 0xff, 0xc6, 0x26, 0x74,
	0x5b, 0x3e, 0x28, 0x9c, 0x54, 0x2e, 0x4e, 0xb5, 0xdf, 0x67, 0xac, 0xb5, 0x23, 0x55, 0xab, 0x38,
	0xf9, 0x6a, 0x48, 0xf7, 0x29, 0x8e, 0xd2, 0x01, 0x65, 0xd6, 0x18, 0x83, 0xfe, 0x61, 0xd0, 0xa3,
	0x95, 0xd0, 0x40, 0xc0, 0x79, 0xb1, 0x5a, 0x79, 0x06, 0x1b, 0xc1, 0x5e, 0x7a, 0x7c, 0x2d, 0x8c,
	0x58, 0x60, 0xc4, 0xb3, 0x55, 0xc4, 0x5b, 0x41, 0xc7, 0xc1, 0x19, 0x56, 0xc0, 0x17, 0x37, 0xcb,
	0xf8, 0xc5, 0x7c, 0xfc, 0xb6, 0xa0, 0x0b, 0xf9, 0x69, 0x96, 0x62, 0x81, 0x2d, 0xbe, 0xfb, 0x07,
	0xbe, 0x64, 0x66, 0xf1, 0x97, 0x59, 0xe8, 0xab, 0x2c, 0xee, 0x92, 0x52, 0xee, 0xb2, 0x8c, 0xa8,
	0x74, 0x41, 0x85, 0xa7, 0x99, 0x41, 0x89, 0x19, 0x1c, 0xe7, 0x34, 0xe0, 0x60, 0x91, 0xa0, 0x18,
	0x60, 0x93, 0xad, 0x21, 0x71, 0xef, 0x7f, 0x0c, 0x7b, 0x9e, 0x6b, 0x99, 0xa9, 0x5b, 0x67, 0x69,
	0xc1, 0x70, 0xe2, 0x97, 0xd3, 0x0d, 0x5e, 0x30, 0x33, 0xf9, 0x9f, 0x6f, 0x38, 0xed, 0xa4, 0x34,
	0x1c, 0xce, 0x12, 0x62, 0xd0, 0x4b, 0xf8, 0x53, 0x62, 0x9b, 0x72, 0xbe, 0x5e, 0x3a, 0xa2, 0x30,
	0xec, 0x25, 0x43, 0x6b, 0x5d, 0x4f, 0x66, 0xaa, 0x3c, 0x9d, 0xa9, 0xf2, 0xf7, 0x4c, 0x95, 0xdf,
	0xe7, 0xaa, 0x34, 0x9d, 0xab, 0xd2, 0xc7, 0x5c, 0x95, 0x9e, 0x9a, 0x96, 0x4d, 0x5f, 0x87, 0x03,
	0xcd, 0xc4, 0xae, 0x2e, 0x7a, 0xe9, 0xd1, 0x2f, 0x7e, 0x8b, 0x43, 0x3a, 0xf6, 0x20, 0x19, 0x94,
	0xd8, 0x97, 0xbd, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x63, 0x76, 0x91, 0x7a, 0x06, 0x05, 0x00,
	0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InstanceOwnerList) > 0 {
		for iNdEx := len(m.InstanceOwnerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InstanceOwnerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.CollectionOwnerList) > 0 {
		for iNdEx := len(m.CollectionOwnerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CollectionOwnerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.ClassTemplateList) > 0 {
		for iNdEx := len(m.ClassTemplateList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClassTemplateList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.PowerupList) > 0 {
		for iNdEx := len(m.PowerupList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PowerupList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.PowerupTemplateList) > 0 {
		for iNdEx := len(m.PowerupTemplateList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PowerupTemplateList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ContributionList) > 0 {
		for iNdEx := len(m.ContributionList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ContributionList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.MintStrategyList) > 0 {
		for iNdEx := len(m.MintStrategyList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MintStrategyList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ClassList) > 0 {
		for iNdEx := len(m.ClassList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClassList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.CollectionList) > 0 {
		for iNdEx := len(m.CollectionList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CollectionList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CollectionList) > 0 {
		for _, e := range m.CollectionList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ClassList) > 0 {
		for _, e := range m.ClassList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.MintStrategyList) > 0 {
		for _, e := range m.MintStrategyList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ContributionList) > 0 {
		for _, e := range m.ContributionList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PowerupTemplateList) > 0 {
		for _, e := range m.PowerupTemplateList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PowerupList) > 0 {
		for _, e := range m.PowerupList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ClassTemplateList) > 0 {
		for _, e := range m.ClassTemplateList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CollectionOwnerList) > 0 {
		for _, e := range m.CollectionOwnerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.InstanceOwnerList) > 0 {
		for _, e := range m.InstanceOwnerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionList = append(m.CollectionList, Collection{})
			if err := m.CollectionList[len(m.CollectionList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassList = append(m.ClassList, Class{})
			if err := m.ClassList[len(m.ClassList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintStrategyList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintStrategyList = append(m.MintStrategyList, MintStrategy{})
			if err := m.MintStrategyList[len(m.MintStrategyList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributionList = append(m.ContributionList, Contribution{})
			if err := m.ContributionList[len(m.ContributionList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowerupTemplateList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PowerupTemplateList = append(m.PowerupTemplateList, PowerupTemplate{})
			if err := m.PowerupTemplateList[len(m.PowerupTemplateList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowerupList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PowerupList = append(m.PowerupList, Powerup{})
			if err := m.PowerupList[len(m.PowerupList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassTemplateList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassTemplateList = append(m.ClassTemplateList, ClassTemplate{})
			if err := m.ClassTemplateList[len(m.ClassTemplateList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionOwnerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionOwnerList = append(m.CollectionOwnerList, CollectionOwner{})
			if err := m.CollectionOwnerList[len(m.CollectionOwnerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceOwnerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InstanceOwnerList = append(m.InstanceOwnerList, InstanceOwner{})
			if err := m.InstanceOwnerList[len(m.InstanceOwnerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
