// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: moonloop/powerup.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Powerup struct {
	CollectionIndex      string     `protobuf:"bytes,1,opt,name=collectionIndex,proto3" json:"collectionIndex,omitempty"`
	ClassIndex           string     `protobuf:"bytes,2,opt,name=classIndex,proto3" json:"classIndex,omitempty"`
	PowerupTemplateIndex string     `protobuf:"bytes,3,opt,name=powerupTemplateIndex,proto3" json:"powerupTemplateIndex,omitempty"`
	InstanceIndex        string     `protobuf:"bytes,4,opt,name=instanceIndex,proto3" json:"instanceIndex,omitempty"`
	Balance              types.Coin `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance"`
	StartTime            int32      `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int32      `protobuf:"varint,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
	NumActivations       int32      `protobuf:"varint,8,opt,name=numActivations,proto3" json:"numActivations,omitempty"`
	Fees                 types.Coin `protobuf:"bytes,9,opt,name=fees,proto3" json:"fees"`
	AcceptingPower       bool       `protobuf:"varint,10,opt,name=acceptingPower,proto3" json:"acceptingPower,omitempty"`
	Creator              string     `protobuf:"bytes,11,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Powerup) Reset()         { *m = Powerup{} }
func (m *Powerup) String() string { return proto.CompactTextString(m) }
func (*Powerup) ProtoMessage()    {}
func (*Powerup) Descriptor() ([]byte, []int) {
	return fileDescriptor_c512482da0d05eb5, []int{0}
}
func (m *Powerup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Powerup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Powerup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Powerup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Powerup.Merge(m, src)
}
func (m *Powerup) XXX_Size() int {
	return m.Size()
}
func (m *Powerup) XXX_DiscardUnknown() {
	xxx_messageInfo_Powerup.DiscardUnknown(m)
}

var xxx_messageInfo_Powerup proto.InternalMessageInfo

func (m *Powerup) GetCollectionIndex() string {
	if m != nil {
		return m.CollectionIndex
	}
	return ""
}

func (m *Powerup) GetClassIndex() string {
	if m != nil {
		return m.ClassIndex
	}
	return ""
}

func (m *Powerup) GetPowerupTemplateIndex() string {
	if m != nil {
		return m.PowerupTemplateIndex
	}
	return ""
}

func (m *Powerup) GetInstanceIndex() string {
	if m != nil {
		return m.InstanceIndex
	}
	return ""
}

func (m *Powerup) GetBalance() types.Coin {
	if m != nil {
		return m.Balance
	}
	return types.Coin{}
}

func (m *Powerup) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Powerup) GetEndTime() int32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Powerup) GetNumActivations() int32 {
	if m != nil {
		return m.NumActivations
	}
	return 0
}

func (m *Powerup) GetFees() types.Coin {
	if m != nil {
		return m.Fees
	}
	return types.Coin{}
}

func (m *Powerup) GetAcceptingPower() bool {
	if m != nil {
		return m.AcceptingPower
	}
	return false
}

func (m *Powerup) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Powerup)(nil), "cosmonaut.moonloop.moonloop.Powerup")
}

func init() { proto.RegisterFile("moonloop/powerup.proto", fileDescriptor_c512482da0d05eb5) }

var fileDescriptor_c512482da0d05eb5 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x31, 0xaf, 0xd3, 0x30,
	0x10, 0xc7, 0x63, 0x5e, 0xdf, 0x4b, 0xeb, 0x0a, 0x90, 0xac, 0x0a, 0x99, 0x82, 0x4c, 0x84, 0x10,
	0xca, 0xe4, 0xa8, 0xed, 0xc4, 0x48, 0x59, 0x60, 0x43, 0x51, 0x27, 0x36, 0xc7, 0x35, 0xc1, 0x52,
	0xe2, 0x8b, 0x62, 0xa7, 0x94, 0x6f, 0xc1, 0x37, 0x62, 0xed, 0xd8, 0x91, 0x09, 0xa1, 0xf6, 0x8b,
	0xa0, 0x38, 0x4d, 0x0b, 0x15, 0xc3, 0xdb, 0xee, 0xfe, 0xff, 0xdf, 0x25, 0x77, 0xe7, 0xc3, 0x4f,
	0x4a, 0x00, 0x53, 0x00, 0x54, 0x49, 0x05, 0x5f, 0x55, 0xdd, 0x54, 0xbc, 0xaa, 0xc1, 0x01, 0x79,
	0x26, 0xc1, 0x96, 0x60, 0x44, 0xe3, 0x78, 0x4f, 0x9c, 0x83, 0xe9, 0x24, 0x87, 0x1c, 0x3c, 0x97,
	0xb4, 0x51, 0x57, 0x32, 0x65, 0xbe, 0xc4, 0x26, 0x99, 0xb0, 0x2a, 0xd9, 0xcc, 0x32, 0xe5, 0xc4,
	0x2c, 0x91, 0xa0, 0x4d, 0xe7, 0xbf, 0xfc, 0x71, 0x83, 0xc3, 0x8f, 0xdd, 0x4f, 0x48, 0x8c, 0x1f,
	0x4b, 0x28, 0x0a, 0x25, 0x9d, 0x06, 0xf3, 0xc1, 0xac, 0xd5, 0x96, 0xa2, 0x08, 0xc5, 0xa3, 0xf4,
	0x5a, 0x26, 0x0c, 0x63, 0x59, 0x08, 0x6b, 0x3b, 0xe8, 0x81, 0x87, 0xfe, 0x52, 0xc8, 0x1c, 0x4f,
	0x4e, 0x9d, 0xaf, 0x54, 0x59, 0x15, 0xc2, 0xa9, 0x8e, 0xbc, 0xf1, 0xe4, 0x7f, 0x3d, 0xf2, 0x0a,
	0x3f, 0xd4, 0xc6, 0x3a, 0x61, 0xe4, 0x09, 0x1e, 0x78, 0xf8, 0x5f, 0x91, 0xbc, 0xc1, 0x61, 0x26,
	0x8a, 0x36, 0xa7, 0xb7, 0x11, 0x8a, 0xc7, 0xf3, 0xa7, 0xbc, 0x9b, 0x90, 0xb7, 0x13, 0xf2, 0xd3,
	0x84, 0xfc, 0x1d, 0x68, 0xb3, 0x1c, 0xec, 0x7e, 0xbd, 0x08, 0xd2, 0x9e, 0x27, 0xcf, 0xf1, 0xc8,
	0x3a, 0x51, 0xbb, 0x95, 0x2e, 0x15, 0xbd, 0x8b, 0x50, 0x7c, 0x9b, 0x5e, 0x04, 0x42, 0x71, 0xa8,
	0xcc, 0xda, 0x7b, 0xa1, 0xf7, 0xfa, 0x94, 0xbc, 0xc6, 0x8f, 0x4c, 0x53, 0xbe, 0x95, 0x4e, 0x6f,
	0x44, 0xbb, 0x02, 0x4b, 0x87, 0x1e, 0xb8, 0x52, 0xc9, 0x02, 0x0f, 0x3e, 0x2b, 0x65, 0xe9, 0xe8,
	0x7e, 0x7d, 0x79, 0xb8, 0xfd, 0xb8, 0x90, 0x52, 0x55, 0x4e, 0x9b, 0xdc, 0xbf, 0x03, 0xc5, 0x11,
	0x8a, 0x87, 0xe9, 0x95, 0xda, 0xb6, 0x27, 0x6b, 0x25, 0x1c, 0xd4, 0x74, 0xec, 0xf7, 0xd2, 0xa7,
	0xcb, 0xf7, 0xbb, 0x03, 0x43, 0xfb, 0x03, 0x43, 0xbf, 0x0f, 0x0c, 0x7d, 0x3f, 0xb2, 0x60, 0x7f,
	0x64, 0xc1, 0xcf, 0x23, 0x0b, 0x3e, 0xf1, 0x5c, 0xbb, 0x2f, 0x4d, 0xc6, 0x25, 0x94, 0xc9, 0xf9,
	0x72, 0x92, 0xf3, 0x6d, 0x6d, 0x2f, 0xa1, 0xfb, 0x56, 0x29, 0x9b, 0xdd, 0xf9, 0x93, 0x58, 0xfc,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x0c, 0x96, 0x9a, 0x7f, 0x02, 0x00, 0x00,
}

func (m *Powerup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Powerup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Powerup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintPowerup(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x5a
	}
	if m.AcceptingPower {
		i--
		if m.AcceptingPower {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	{
		size, err := m.Fees.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPowerup(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.NumActivations != 0 {
		i = encodeVarintPowerup(dAtA, i, uint64(m.NumActivations))
		i--
		dAtA[i] = 0x40
	}
	if m.EndTime != 0 {
		i = encodeVarintPowerup(dAtA, i, uint64(m.EndTime))
		i--
		dAtA[i] = 0x38
	}
	if m.StartTime != 0 {
		i = encodeVarintPowerup(dAtA, i, uint64(m.StartTime))
		i--
		dAtA[i] = 0x30
	}
	{
		size, err := m.Balance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPowerup(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.InstanceIndex) > 0 {
		i -= len(m.InstanceIndex)
		copy(dAtA[i:], m.InstanceIndex)
		i = encodeVarintPowerup(dAtA, i, uint64(len(m.InstanceIndex)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PowerupTemplateIndex) > 0 {
		i -= len(m.PowerupTemplateIndex)
		copy(dAtA[i:], m.PowerupTemplateIndex)
		i = encodeVarintPowerup(dAtA, i, uint64(len(m.PowerupTemplateIndex)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ClassIndex) > 0 {
		i -= len(m.ClassIndex)
		copy(dAtA[i:], m.ClassIndex)
		i = encodeVarintPowerup(dAtA, i, uint64(len(m.ClassIndex)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CollectionIndex) > 0 {
		i -= len(m.CollectionIndex)
		copy(dAtA[i:], m.CollectionIndex)
		i = encodeVarintPowerup(dAtA, i, uint64(len(m.CollectionIndex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPowerup(dAtA []byte, offset int, v uint64) int {
	offset -= sovPowerup(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Powerup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CollectionIndex)
	if l > 0 {
		n += 1 + l + sovPowerup(uint64(l))
	}
	l = len(m.ClassIndex)
	if l > 0 {
		n += 1 + l + sovPowerup(uint64(l))
	}
	l = len(m.PowerupTemplateIndex)
	if l > 0 {
		n += 1 + l + sovPowerup(uint64(l))
	}
	l = len(m.InstanceIndex)
	if l > 0 {
		n += 1 + l + sovPowerup(uint64(l))
	}
	l = m.Balance.Size()
	n += 1 + l + sovPowerup(uint64(l))
	if m.StartTime != 0 {
		n += 1 + sovPowerup(uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		n += 1 + sovPowerup(uint64(m.EndTime))
	}
	if m.NumActivations != 0 {
		n += 1 + sovPowerup(uint64(m.NumActivations))
	}
	l = m.Fees.Size()
	n += 1 + l + sovPowerup(uint64(l))
	if m.AcceptingPower {
		n += 2
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovPowerup(uint64(l))
	}
	return n
}

func sovPowerup(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPowerup(x uint64) (n int) {
	return sovPowerup(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Powerup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPowerup
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Powerup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Powerup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPowerup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPowerup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPowerup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPowerup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowerupTemplateIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPowerup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPowerup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PowerupTemplateIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPowerup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPowerup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InstanceIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPowerup
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPowerup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			m.EndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTime |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumActivations", wireType)
			}
			m.NumActivations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumActivations |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPowerup
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPowerup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptingPower", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AcceptingPower = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPowerup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPowerup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPowerup(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPowerup
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPowerup(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPowerup
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPowerup
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPowerup
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPowerup
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPowerup
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPowerup        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPowerup          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPowerup = fmt.Errorf("proto: unexpected end of group")
)
